version: '2'
services:
  web:
    restart: always
    build: ./web
    expose:
      - "3000"
    links:
      - mongodb:mongodb
    volumes:
      - /usr/src/app/static
    depends_on:
        - mongodb
    command: node server.js

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web
    command: /usr/sbin/nginx

  mongodb:
    restart: always
    image: mongodb



#http://containertutorials.com/docker-compose/nginx-flask-postgresql.html
